### PR TITLE
fix: Handle wildcard rootHost values

### LINKED ISSUE #88: bug: wildcards records are not added as expected
when using a wildcard hostname with distributed DNS, the DNSRecord structure looks correct but it differs from what is actually added to route53

to see this issue create a loadbalanced dns policy and/or resulting dns record. 

You will see it has the right endpoints

```
endpoints:
    - dnsName: '*.managed.hcpapps.net'
      recordTTL: 300
      recordType: CNAME
      targets:
        - klb.managed.hcpapps.net
    - dnsName: default.klb.managed.hcpapps.net
      providerSpecific:
        - name: weight
          value: '120'
      recordTTL: 60
      recordType: CNAME
      setIdentifier: a6e65a17553d94a18a87ac384f734e8b-1159838119.us-east-1.elb.amazonaws.com
      targets:
        - >-
          a6e65a17553d94a18a87ac384f734e8b-1159838119.us-east-1.elb.amazonaws.com
    - dnsName: klb.managed.hcpapps.net
      providerSpecific:
        - name: geo-code
          value: '*'
      recordTTL: 300
      recordType: CNAME
      setIdentifier: default
      targets:
        - default.klb.managed.hcpapps.net
      
```

but in AWS it looks different

### PR DESCRIPTION
**Pull request by mikenairn**
closes #88 

Fixes an issue where if you specify a wildcard rootHost value e.g. *.example.com the plan would incorrectly filter out changes for valid dnsNames e.g. foo.example.com, and only create exactly matching dnsNames e.g. *.example.com.

### CODE REVIEW

File: test/e2e/single_record_test.go [hunk 1]
```diff
@@ -53,6 +53,83 @@ var _ = Describe("Single Record Test", func() {
...
+			})),
+			PointTo(MatchFields(IgnoreExtras, Fields{
+				"DNSName":       Equal(testHostname2),
+				"Targets":       ConsistOf(testTargetIP2),
+				"RecordType":    Equal("A"),
+				"SetIdentifier": Equal(""),
+				"RecordTTL":     Equal(externaldnsendpoint.TTL(60)),
+			})),
+		))
+	})
```
Comment (mikenairn) [inline test/e2e/single_record_test.go:131]: We have no way of verifying this from the integration test at the moment. Added e2e test for the time being.

File: internal/controller/dnsrecord_controller.go [hunk 2]
```diff
@@ -301,7 +301,7 @@ func (r *DNSRecordReconciler) applyChanges(ctx context.Context, dnsRecord *v1alp
 	logger := log.FromContext(ctx)
 	filterDomain, _ := strings.CutPrefix(managedZone.Spec.DomainName, v1alpha1.WildcardPrefix)
 	if dnsRecord.Spec.RootHost != nil {
-		filterDomain = *dnsRecord.Spec.RootHost
+		filterDomain, _ = strings.CutPrefix(*dnsRecord.Spec.RootHost, v1alpha1.WildcardPrefix)
```
Comment (mikenairn) [inline internal/controller/dnsrecord_controller.go:304]: We might want to consider adding validation onto the `rootHost` CRD field.

**Review by maleck13 — APPROVED** [review]
